# Generated by Django 5.0.6 on 2024-11-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_price_category'),
        ('payments', '0002_rename_name_payment_patient_name_payment_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment'),
        ),
    ]
