# Generated by Django 5.0.6 on 2024-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price_category',
            field=models.IntegerField(choices=[(1, 'Standard - NPR 500'), (2, 'Premium - NPR 1000'), (3, 'VIP - NPR 1500')], default=1),
        ),
    ]
